### ISSUE TITLE
Разделить ключи и представления - аналогично спискам значений

### ISSUE THREAD

**Issue by artbear** [240596448/cli-selector#2]
Было бы удобно разделить ключи и представления элементов выбора.
Пользователь видит представление элемента, а в результат попадают ключи.

в дополнение к этой фиче было бы полезно загружать списки значений для выбора
- значение - это ключ
- представление - представление
- пометка - это флаг использования

Например, `ДобавитьСписокДляВыбора(Знач Список);`

**Comment by 240596448** [comment]
Возможно пригодится. Согласен.

**Comment by 240596448** [comment]
Представления добавлены [v0.3.0](https://github.com/240596448/cli-selector/releases/tag/v0.3.0)

**Comment by 240596448** [comment]
Дополнительный метод а-ля `ДобавитьСписокДляВыбора(Знач Список)` не стал делать. Он видится избыточным.

Класс создает ТаблицуЗначений, существующий метод наполняет ее строки... Достаточно компактный код для инициализации и выбора.
А если делать сначала создание списка, потом его передачу, а потом перезаполнение из него в данные класса, то создание списка дублирует функционал класса и увеличивает код почти вдвое.
