### ISSUE TITLE
Возможность использования произвольных значений для выбора - пользователь видит представление, а в результатах выбора возвращается само значение любого типа

### ISSUE THREAD

**Issue by artbear** [240596448/cli-selector#4]
в продолжение #2 

хорошо бы дать эту возможность
опять же аналогично СписокЗначений

тогда не пришлось бы городить костыли с поиском значений после выбора
например, как сейчас сделано в ПР для Ванесса-раннер 
https://github.com/vanessa-opensource/vanessa-runner/pull/453/files#diff-b734a2023612e44277e5dae7595f98766b69ed4114f697e833a3346737f86537R120-R125
```bsl
//элемент приходится добавлять так 
// ВыборВКонсоли.ДобавитьЗначениеВыбора(Пакет.Имя, Пакет.Имя, Пакет.Использовать);
Пакеты = ВыбратьПакеты(ПакетыУстановки);
Для Каждого СтрокаПакета Из ПакетыУстановки Цикл // коллекция всех пакетов

	Пакет = ДанныеПакета(СтрокаПакета);	
	Если Пакеты.Найти(Пакет.Имя) = Неопределено Тогда // и тут повторно приходится искать
```

а удобен был бы простой вариант
```bsl
ВыборВКонсоли.ДобавитьЗначениеВыбора(Пакет, Пакет.Имя, Пакет.Использовать);

Пакеты = ВыбратьПакеты(ПакетыУстановки);

Для Каждого Пакет Из Пакеты Цикл
```

**Comment by artbear** [comment]
@240596448 и естественно, нужно учитывать, что 2го параметра (Представления) может не быть, и тогда нужно приводить 1й параметр к строке и использовать как представление.

**Comment by 240596448** [comment]
[v0.4.0](https://github.com/240596448/cli-selector/releases/tag/v0.4.0)
