### ISSUE TITLE
Добавление списка значений для выбора

### ISSUE THREAD

**Issue by artbear** [240596448/cli-selector#5]
я все-таки решил выделить эту задачу как отдельную из https://github.com/240596448/cli-selector/issues/2

в дополнение к этой фиче было бы полезно загружать списки значений для выбора
- значение - это ключ
- представление - представление
- пометка - это флаг использования

Например, `ДобавитьСписокДляВыбора(Знач Список)`

Параметр-Список в данном случае только коллекция с исходными данными.

Реализация метода крайне простая, никаких сложностей, просто добавление элементов через основной метод добавления.

сейчас выложу ПР

**Comment by 240596448** [comment]
_Реализация метода крайне простая, никаких сложностей, просто добавление элементов через основной метод добавления._
Тут вопрос был не в простоте, а в моем понимании построения апи. 
Как по мне - это частный случай, код которого нужно реализовывать в приложении. Да, он будет повторяться в разных приложениях, но тем не менее...
Или делать универсальное добавление произвольной коллекции (желательно через `заполнить значения свойств`) или оставлять эти три строки приложениям.

У каждого впрочем свое мнение)) Хочется - значит пусть будет.
